version: '3'
# Commands for Build and Start:
# docker-compose -f app/docker-compose.dev.yml build
# docker-compose -f app/docker-compose.dev.yml up -d

services:
  app:
    build: ./app
    container_name: flask_azz_yt
    command: gunicorn --bind 0.0.0.0:5000 app:app
    environment:
      - DATABASE_URL= "" # connect to Yandex
    volumes:
      - ./app:/app
    expose:
      - 5000
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bubnov
      - POSTGRES_PASSWORD=bubnov
      - POSTGRES_DB=bubnov_db
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=andreybybnov435@yandex.ru
      - PGADMIN_DEFAULT_PASSWORD=bubnov
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0 # machine IP
      - PGADMIN_LISTEN_PORT=5555
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./static:/home/web/default/static
    depends_on:
      - app
      - pgadmin